/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    copy: (typeof import("./components/s-layout-search/index copy.vue"))["default"];
    "Index copy": (typeof import("./components/s-layout-search/index copy.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SBarcodeDraw: (typeof import("./components/s-barcode-draw/index.vue"))["default"];
    SCodeView: (typeof import("./components/s-code-view/index.vue"))["default"];
    SExternalLinkPage: (typeof import("./components/s-external-link-page/index.vue"))["default"];
    SFoldPage: (typeof import("./components/s-fold-page/index.vue"))["default"];
    SFullPage: (typeof import("./components/s-full-page/index.vue"))["default"];
    SInternalLinkPage: (typeof import("./components/s-internal-link-page/index.vue"))["default"];
    SLangProvider: (typeof import("./components/s-lang-provider/index.vue"))["default"];
    SLayoutSearch: (typeof import("./components/s-layout-search/index.vue"))["default"];
    SLayoutTools: (typeof import("./components/s-layout-tools/index.vue"))["default"];
    SMainTransition: (typeof import("./components/s-main-transition/index.vue"))["default"];
    SPinyinPro: (typeof import("./components/s-pinyin-pro/index.vue"))["default"];
    SQrcodeDraw: (typeof import("./components/s-qrcode-draw/index.vue"))["default"];
    SRecorderPcm: (typeof import("./components/s-recorder-pcm/index.vue"))["default"];
    SSelectIcon: (typeof import("./components/s-select-icon/index.vue"))["default"];
    SSvgAndIcon: (typeof import("./components/s-svg-and-icon/index.vue"))["default"];
    SSvgIcon: (typeof import("./components/s-svg-icon/index.vue"))["default"];
    SVerifyCode: (typeof import("./components/s-verify-code/index.vue"))["default"];
    TAside: (typeof import("tdesign-vue-next"))["Aside"];
    TBadge: (typeof import("tdesign-vue-next"))["Badge"];
    TBreadcrumb: (typeof import("tdesign-vue-next"))["Breadcrumb"];
    TBreadcrumbItem: (typeof import("tdesign-vue-next"))["BreadcrumbItem"];
    TButton: (typeof import("tdesign-vue-next"))["Button"];
    TCheckbox: (typeof import("tdesign-vue-next"))["Checkbox"];
    TColorPicker: (typeof import("tdesign-vue-next"))["ColorPicker"];
    TContent: (typeof import("tdesign-vue-next"))["Content"];
    TDivider: (typeof import("tdesign-vue-next"))["Divider"];
    TDrawer: (typeof import("tdesign-vue-next"))["Drawer"];
    TDropdown: (typeof import("tdesign-vue-next"))["Dropdown"];
    TDropdownItem: (typeof import("tdesign-vue-next"))["DropdownItem"];
    TEmpty: (typeof import("tdesign-vue-next"))["Empty"];
    TFooter: (typeof import("tdesign-vue-next"))["Footer"];
    TForm: (typeof import("tdesign-vue-next"))["Form"];
    TFormItem: (typeof import("tdesign-vue-next"))["FormItem"];
    THeader: (typeof import("tdesign-vue-next"))["Header"];
    THeadMenu: (typeof import("tdesign-vue-next"))["HeadMenu"];
    TIcon: (typeof import("tdesign-vue-next"))["Icon"];
    TImage: (typeof import("tdesign-vue-next"))["Image"];
    TInput: (typeof import("tdesign-vue-next"))["Input"];
    TLayout: (typeof import("tdesign-vue-next"))["Layout"];
    TMenu: (typeof import("tdesign-vue-next"))["Menu"];
    TMenuItem: (typeof import("tdesign-vue-next"))["MenuItem"];
    TOption: (typeof import("tdesign-vue-next"))["Option"];
    TPopup: (typeof import("tdesign-vue-next"))["Popup"];
    TSelect: (typeof import("tdesign-vue-next"))["Select"];
    TSlider: (typeof import("tdesign-vue-next"))["Slider"];
    TSpace: (typeof import("tdesign-vue-next"))["Space"];
    TSubmenu: (typeof import("tdesign-vue-next"))["Submenu"];
    TSwitch: (typeof import("tdesign-vue-next"))["Switch"];
    TTabPanel: (typeof import("tdesign-vue-next"))["TabPanel"];
    TTabs: (typeof import("tdesign-vue-next"))["Tabs"];
    TTooltip: (typeof import("tdesign-vue-next"))["Tooltip"];
  }
}
